sudo: required
services:
- docker

language: python
python:
- "2.7"
install:
- pip install -r requirements.txt
script:
- python -m pytest -v

jobs:
  include:
    - stage: deploy to dockerhub
      before_script:
      - docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH .
      - docker run --rm -p 5000:5000 -d $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH
      script:
       - curl -X GET http://localhost:5000
       - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker push $TRAVIS_REPO_SLUG

    - stage: deploy to s3 and codedeploy
      deploy:
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        local_dir: pythontest
        skip_cleanup: true
        on: &2
        bucket: travisdeploy-s3
        region: us-east-2

      - provider: codedeploy
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: travisdeploy-s3
        key: latest.zip
        bundle_type: zip
        application: travisdeploy-app
        deployment_group: travisdeploy-group
        region: us-east-2
        on: *2
      script:
        - zip -r latest *
        - mkdir -p pythontest
        - mv latest.zip pythontest/latest.zip
